### ISSUE TITLE
Allow notifications to be registered with a decorator

### ISSUE THREAD

**Issue by jproffitt** [worthwhile/django-herald#18]
This is how you register now:

    class MyEmail(EmailNotification):
        ...
    registry.register(MyEmail)

Would be nice if you could also do this:

    @registry.register
    class MyEmail(EmailNotification):
        ...

**Comment by raiderrobert** [comment]
+1

**Comment by jproffitt** [comment]
This is fixed in https://github.com/worthwhile/django-herald/pull/26.
