### ISSUE TITLE
Adding attachments is not well documented

### ISSUE THREAD

**Issue by saranshbansal** [worthwhile/django-herald#54]
As per the readme section, the attachment can be in the form of Django File object. 
Now, I have created a Django File object as follows:

        with open('docs/my.pdf', 'r') as f:
            file = File(f)

I am having a hard time figuring out how to use this object in the code to send the email. Anything done outside the `with` block obviously creates an error as the file is closed.

Here is the full code: 
```
@registry.register_decorator()
class SendThisMail(SomeBaseClass, EmailNotification):
    def __init__(self, user, my_modal: models.MyModal):
        super().__init__(user, my_modal)

        self.subject = "abc"

        with open('docs/my.pdf', 'r') as f:
            file = File(f)

            self.attachments = (
                'abc.pdf', file,
                'application/pdf')

        self.context = {
            'subject': self.subject,
            **self.context,
        }

        self.to_emails = [user.email]

def sendMail():
    SendThisMail(user, my_modal).send(user=my_user) # creates an error on this line as the file object is closed and inaccessible.

```

**Comment by saranshbansal** [comment]
Made it work after wasting 2 days!

@registry.register_decorator()
class SendThisMail(SomeBaseClass, EmailNotification):
    def __init__(self, user, my_modal: models.MyModal):
        super().__init__(user, my_modal)

        self.subject = "abc"

        file = open('docs/my.pdf', 'r').read() <- the magic code. Please document it well.

        self.attachments = [('abc.pdf', file, 'application/pdf')]

        self.context = {
            'subject': self.subject,
            **self.context,
        }

        self.to_emails = [user.email]

def sendMail():
    SendThisMail(user, my_modal).send(user=my_user)

**Comment by jproffitt** [comment]
Thank you for the report! I never encountered that before, but it makes sense. I’ll update the readme and/or see if I can make it work the way the readme mentions

**Comment by jproffitt** [comment]
This was fixed in https://github.com/worthwhile/django-herald/pull/58. You can not add attachments that are already closed.
