### ISSUE TITLE
Configuring email host

### ISSUE THREAD

**Issue by bralbral** [worthwhile/django-herald#62]
Hello! I ask for help! It’s not clear from the description how to set up an email account from where messages will be sent. For example, I have a gmail mailbox. How do I send from there? Where can I set login parameters for my account? Thank!

**Comment by raiderrobert** [comment]
django-herald doesn't handle that problem directly. It wraps the existing
email backends in Django:
https://docs.djangoproject.com/en/3.0/topics/email/#smtp-backend

**Comment by bralbral** [comment]
Thank you for such a quick response, the problem was solved!
