### ISSUE TITLE
confusing 'delnotifs' command with optional start and end args

### ISSUE THREAD

**Issue by pzmosquito** [worthwhile/django-herald#71]
for `delnotifs` command with `start` and `end` args, doc says:
```
end is up to, but not including that date.
```

I'd think if I specify the `end` date being yesterday without `start` date, it will delete notifications sent before yesterday.

the actual code is
```python
start_date = options['start'] if options['start'] else today
```

This will set the `start` date to be today, and `end` date to be yesterday, it's going to be an invalid range.

Suggestion:
- if only `end` date is specified, delete anything sent before `date_sent`
- if only `start` date is specified, delete anything sent after `date_sent`
- if both `start` and `end` dates are specified, delete the range

**Comment by peterfarrell** [comment]
@pzmosquito PRs are welcome.

**Comment by pzmosquito** [comment]
PR https://github.com/worthwhile/django-herald/pull/72 submitted

**Comment by pzmosquito** [comment]
PR merged
