### ISSUE TITLE
Add peterfarrell-atdsaa on PyPI as maintainer

### ISSUE THREAD

**Issue by peterfarrell** [worthwhile/django-herald#80]
@raiderrobert @georgmzimmer @mands

We are sprinting on Django-Herald at DjangoCon 2022 latter this week.  Could one of you make `peterfarrell-atdsaa` a maintainer on PyPi so we can make a release?

https://pypi.org/project/django-herald/

If we don't hear from you, we will fork this project to `django-heralder` and consider the efforts on this repo / PyPi no longer maintained.

**Comment by raiderrobert** [comment]
@peterfarrell unfortunately, I am not an owner. I'm only a maintainer, so I can't add you. I think only another dev is the owner at this point. 

That said, since there is interest, I can try to prioritize a release since I still have that access.

**Comment by mluard** [comment]
Thanks for the ping @raiderrobert and for the interest @peterfarrell.  PyPi maintainer invite has been sent.

**Comment by peterfarrell** [comment]
@mluard - thanks! Release 0.3.0 already made, swapped over to GH Actions, support for Django 4.x, among others...
